name: Publish Docker image to GHCR

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags like v1.2.3

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed to push to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN has packages:write permission

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }} # Use the repository name for the image name
          tags: |
            # Get the version from the tag pushed
            type=semver,pattern={{version}}
            # Also tag with major.minor
            type=semver,pattern={{major}}.{{minor}}
            # Tag as latest if it's the newest tag (optional)
            type=edge,branch=main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: . # Use the current directory as build context
          file: ./Dockerfile # Specify the Dockerfile location
          push: true # Push the image after building
          tags: ${{ steps.meta.outputs.tags }} # Use tags generated by the metadata action
          labels: ${{ steps.meta.outputs.labels }} # Add labels generated by the metadata action
          cache-from: type=gha
          cache-to: type=gha,mode=max

